micronaut:
  application:
    name: medication-catalog-service
  server:
    port: 8080
    host: localhost

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

logger:
  levels:
    com.example: DEBUG
    root: INFO